-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 96fb7fa10f2f4c11ed33482a9ad7474251e5e97f
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: 23d995302ef6716c27f10441b9fd3ccb43c1c489
    hooks:
    -   id: yapf
