-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: debug-statements
-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: v0.16.3
    hooks:
    -   id: yapf
-   repo: local
    hooks:
    -   id: isort
        name: Sort imports
        entry: isort
        language: system
        files: \.py$
