---
- name: Configure server
  hosts: all
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo
  environment:
    PYTHONPATH: "{{ django.root }}"
    DJANGO_SETTINGS_MODULE: "{{ django.settings }}"
    DATABASE_URL: postgresql://{{ secret.db_user }}:{{ secret.db_password }}@{{ secret.db_host }}:{{ secret.db_port }}/{{ secret.db_name }}
    SECRET_KEY: "{{ secret.secret_key }}"
    STRIPE_SECRET_KEY: "{{ stripe.secret_key }}"
    STRIPE_PUBLISHABLE_KEY: "{{ stripe.publishable_key }}"
    EMAIL_ADDRESS: "{{ email.address }}"
    EMAIL_PASSWORD: "{{ email.password }}"
    EMAIL_SMTP_SERVER: "{{ email.smtp_server }}"
    EMAIL_SMTP_PORT: "{{ email.smtp_port }}"
    EMAIL_SECURE: "{{ email.secure }}"
    EMAIL_REPLY_TO: "{{ email.reply_to }}"
    EMAIL_ADMINS: "{{ email.admins }}"
  roles:
    - { role: user, tags: user }
    - { role: apt, tags: apt }
    - { role: postgres, tags: postgres }
    - { role: python, tags: python }
    - role: lets-encrypt
      tags: ssl
      letsencrypt_email: "{{ lets_encrypt.email }}"
      letsencrypt_domain: "{{ project.domain }}"
      letsencrypt_request_www: false
      letsencrypt_pause_services:
        - nginx
    - { role: deploy, tags: deploy }
    - { role: nginx, tags: nginx }
