---
- name: Install Python and dependencies
  apt: name={{ item }} state=present
  with_items:
    - python3
    - python3-pip
    - python3-venv
    - python3-virtualenv
    - libxml2
    - libxml2-dev
    - libxslt1.1
    - libxslt1-dev
    - sendmail
    - virtualenv
