---
- name: Install Nginx
  apt: name=nginx state=present
- name: Copy Nginx configuration
  template: src=nginx.conf dest=/etc/nginx/sites-available/{{ project.name }}.conf force=yes
  notify:
    - Restart Nginx
- name: Create Nginx log location
  file: path={{ project.root }}logs state=directory
- name: Remove Nginx default configuration
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - Reload systemd
    - Restart Nginx
- name: Enable project site
  file: src=/etc/nginx/sites-available/{{ project.name }}.conf dest=/etc/nginx/sites-enabled/{{ project.name }}.conf state=link
  notify:
    - Reload systemd
    - Restart Nginx
- name: Make sure Nginx is running
  service: name=nginx enabled=yes state=started
